server {
    listen 80;
    server_name ai-dbc.zeaz.dev;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
        access_log off;
    }

    location / {
        return 404;
    }
}
